# Generated by Django 3.2.21 on 2023-10-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20231030_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telephone',
            field=models.CharField(default='', max_length=14),
        ),
    ]
