# Generated by Django 3.2.25 on 2024-06-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_order_telephone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Stores',
        ),
    ]
