# Generated by Django 3.2.25 on 2024-06-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_store_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instructions',
            field=models.TextField(default='dog'),
            preserve_default=False,
        ),
    ]
