# Generated by Django 3.2.25 on 2024-07-02 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20240606_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 7, 2, 10, 41, 24, 636115, tzinfo=utc)),
        ),
    ]
